apiVersion: v1
appVersion: 1.26.0
description: A Helm chart to run Azure CSI driver for Azure File.
icon: https://s.giantswarm.io/app-icons/azure/1/dark.svg
home: https://github.com/giantswarm/azurefile-csi-driver-app
name: azurefile-csi-driver-app
version: [[ .Version ]]
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [azure]
